### ISSUE TITLE
Bug with kick command.

### ISSUE THREAD

**Issue by LWJerri** [Satont/channelsbot#29]
When I try to send **cc!kick**, ban send me an error.

![image](https://user-images.githubusercontent.com/50290430/103446241-fcc40c00-4c85-11eb-82fd-e80ea0b40d4b.png)

**Comment by Satont** [comment]
Text channel where to use kick should be in the same category, where channels creating.

Also if you need channel admin, it will deny you use that command.

Currently i haven't setuped custom permission name for `kick` command ,thats why there is blank "``".

Please, recheck correctly setuped text channel.

**Comment by LWJerri** [comment]
Okay, thanks for your response!

**Comment by Satont** [comment]
I not said thats a not bug. If it's still not working, you are free to open
this issue again.

сб, 2 янв. 2021 г., 19:14 Andrey <notifications@github.com>:
